# Generated by Django 5.1.3 on 2025-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yili')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rangi')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='Egasi')),
                ('other_info', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
            options={
                'verbose_name': 'GenerateModel',
                'verbose_name_plural': 'GenerateModels',
                'db_table': 'generate',
            },
        ),
    ]
