# Generated by Django 5.1.3 on 2025-06-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatemodel',
            name='processed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='processed_pdfs/'),
        ),
    ]
