# Generated by Django 5.1.3 on 2025-06-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_generatemodel_processed_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatemodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='generatemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='generatemodel',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='generatemodel',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='generatemodel',
            name='processed_pdf',
        ),
        migrations.RemoveField(
            model_name='generatemodel',
            name='year',
        ),
        migrations.AddField(
            model_name='generatemodel',
            name='client',
            field=models.CharField(default=1, max_length=255, verbose_name='Buyurtmachi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatemodel',
            name='input_pdf',
            field=models.FileField(default=1, upload_to='uploads/original_pdfs/', verbose_name='Asl PDF fayl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatemodel',
            name='purpose',
            field=models.CharField(default=1, max_length=255, verbose_name='Baholash maqsadi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatemodel',
            name='result_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/processed_pdfs/', verbose_name='Tayyorlangan PDF'),
        ),
        migrations.AddField(
            model_name='generatemodel',
            name='valuation_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Baholangan narx'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generatemodel',
            name='owner',
            field=models.CharField(default=1, max_length=255, verbose_name='Mulk egasi'),
            preserve_default=False,
        ),
    ]
