# Generated by Django 5.1.3 on 2025-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_generatemodel_color_remove_generatemodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatemodel',
            name='status',
            field=models.CharField(choices=[('downloaded', 'Yuklab olingan'), ('pending', 'Kutilmoqda'), ('error', 'Xatolik')], default='pending', max_length=100, verbose_name='Status'),
        ),
    ]
