# Generated by Django 5.1.3 on 2025-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_generatemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatemodel',
            name='valuation_amount',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Baholangan narx'),
        ),
    ]
